### ISSUE TITLE
Returns entire rule instead of declarations changed within rule

### ISSUE THREAD

**Issue by Jarred-Sumner** [lukemiles/stylesheet-differ#2]
Current output:

```css
body {
  min-height: calc(100vh - 24px);
  line-height: 1;
  font-family: IBMPlexSans, sans-serif;
  -webkit-font-smoothing: antialiased;
}
```

Expected output:

```css
body {
  min-height: calc(100vh - 24px);
}
```
